---

hq:
  children:
    switches:
      children:
        core:
          hosts:
            core-sw01:
            core-sw02:

        access: 
          hosts:
            access-sw01:
            access-sw02:
            access-sw03:
            access-sw04:

    routers:
      hosts:
        edge-rtr01:
        edge-rtr02:
